stderr of test 'dbfarm-foreign-chars.Bug-7031` in directory 'sql/test/BugTracker-2020` itself:


# 10:13:05 >  
# 10:13:05 >  "/usr/bin/python3.9" "dbfarm-foreign-chars.Bug-7031.py" "dbfarm-foreign-chars.Bug-7031"
# 10:13:05 >  


# 10:13:07 >  
# 10:13:07 >  "Done."
# 10:13:07 >  

