stderr of test 'schema_view2.Bug-3766` in directory 'sql/test/BugTracker-2015` itself:


# 16:30:14 >  
# 16:30:14 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=37297" "--set" "mapi_usock=/var/tmp/mtest-2635/.s.monetdb.37297" "--set" "monet_prompt=" "--forcemito" "--set" "mal_listing=2" "--dbpath=/export/scratch2/zhang/monet-install/Jul2015/debug/var/MonetDB/mTests_sql_test_BugTracker-2015" "--set" "mal_listing=0" "--set" "embedded_r=yes"
# 16:30:14 >  

MAPI  = (monetdb) /var/tmp/mtest-367413/.s.monetdb.36874
QUERY = create view tst.v1 (i) as select * from t1;
ERROR = !CREATE VIEW: name 'v1' already in use
CODE  = 42S01

# 16:30:15 >  
# 16:30:15 >  "Done."
# 16:30:15 >  

